name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Run Tests
      run: go test -v ./tests/user_test.go

    - name: Build Go binary
      run: go build -o app main.go

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image with build args
      run: docker buildx build \
             --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
             --build-arg SECRET_KEY=${{ secrets.SECRET_KEY }} \
             -t aryan0011/go-backend:latest \
             --push .
    - name: Push Docker image
      run: docker push aryan0011/go-backend:latest
